routes:
  - path: /api/login
    upstream: http://auth-service:8000/login
    methods: [POST]
    access: public
  - path: /api/user/{id}
    upstream: http://user-service:8001/user/{id}
    methods: [GET]
    access: auth
  - path: /api/admin/stats
    upstream: http://admin-service:8002/stats
    methods: [GET]
    access: admin
    rate_limit:
      rps: 2
      burst: 5
