apiVersion: v1
kind: ConfigMap
metadata:
  name: homenavi-edge-proxy-nginx
  labels:
    {{- include "homenavi.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      include /etc/nginx/routes.conf;
    }
  routes.conf: |
{{ .Files.Get "files/edge-routes.conf" | indent 4 }}