{{- if eq (include "homenavi.jwtStaticSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homenavi.jwtSecretName" . }}
  labels:
    {{- include "homenavi.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_public.pem: |
{{ .Values.jwt.publicKey | indent 4 }}
  jwt_private.pem: |
{{ .Values.jwt.privateKey | indent 4 }}
{{- end }}
