{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homenavi.serviceAccountName" . }}
  labels:
    {{- include "homenavi.labels" . | nindent 4 }}
{{- end }}
