name: Release API Gateway Docker Image

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: ./.github/workflows/service_release.yml
    with:
      service: api-gateway
      context: .
      dockerfile: ./api-gateway/Dockerfile
    secrets: inherit
