name: Build Echo Service Docker Image

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./echo-service
          file: ./echo-service/Dockerfile
          push: false
          tags: homenavi-echo-service:latest

      - name: Save Docker image to tarball
        run: docker save homenavi-echo-service:latest | gzip > homenavi-echo-service-latest.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: homenavi-echo-service-latest
          path: homenavi-echo-service-latest.tar.gz