name: Release MCP Service Docker Image

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: ./.github/workflows/service_release.yml
    with:
      service: mcp-service
      context: .
      dockerfile: ./mcp-service/Dockerfile
    secrets: inherit