name: Release Mock Adapter Docker Image

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: ./.github/workflows/service_release.yml
    with:
      service: mock-adapter
      context: .
      dockerfile: ./mock-adapter/Dockerfile
    secrets: inherit
